version: "3.8"

services:
  app:
    build: .
    container_name: panda-boxes-app
    ports:
      - "${PORT}:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=${PGHOST}
      - DB_PORT=${PGPORT}
      - DB_USER=${PGUSER}
      - DB_PASSWORD=${PGPASSWORD}
      - DB_NAME=${PGDATABASE}
    volumes:
      - .:/panda-boxes-backend

  db:
    image: postgres:15
    container_name: panda-boxes-db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
